apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        ports:
        - containerPort: 8081
        env:
        - name: NEXUS_DB_HOST
          value: "nexus-postgresql"
        - name: NEXUS_DB_PORT
          value: "5432"
        - name: NEXUS_DB_NAME
          value: "nexusdb"
        - name: NEXUS_DB_USER
          value: "nexus"
        - name: NEXUS_DB_PASSWORD
          value: "nexuspassword"
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-storage
      volumes:
      - name: nexus-storage
        persistentVolumeClaim:
          claimName: nexus-pvc
