name: Backup Repositories

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq

      - name: Configure AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1

      - name: Read CSV and Process Repositories
        run: |
          while IFS=, read -r repo branch
          do
            # Extract repo name
            repo_name=$(basename $repo .git)
            
            # Clone the repository and checkout the specified branch
            git clone --branch $branch $repo $repo_name

            # Zip the repository contents
            zip -r ${repo_name}.zip $repo_name

            # Upload to S3
            aws s3 cp ${repo_name}.zip s3://your-s3-bucket/${repo_name}.zip

            # Clean up
            rm -rf $repo_name
            rm ${repo_name}.zip
          done < repositories.csv

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
