name: Backup Repositories

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq

      - name: Configure AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1

      - name: Read CSV and Process Repositories
        run: |
          while IFS=, read -r repo branch
          do
            # Extract repo name
            repo_name=$(basename $repo .git)
            
            # Clone the repository and checkout the specified branch
            git clone --branch $branch $repo $repo_name

            # Zip the repository contents
            zip -r ${repo_name}.zip $repo_name

            # Upload to S3
            aws s3 cp ${repo_name}.zip s3://your-s3-bucket/${repo_name}.zip

            # Clean up
            rm -rf $repo_name
            rm ${repo_name}.zip
          done < repositories.csv

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




      name: Backup Repositories

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout this repository
      - name: Checkout this repository
        uses: actions/checkout@v2

      # Step 2: Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq

      # Step 3: Configure AWS CLI
      - name: Configure AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1

      # Step 4: Verify the CSV file exists
      - name: Verify CSV file exists
        run: |
          if [ ! -f .github/workflows/repositories.csv ]; then
            echo "Error: .github/workflows/repositories.csv not found!"
            exit 1
          else
            echo "CSV file found."
          fi

      # Step 5: Read CSV and Process Repositories
      - name: Read CSV and Process Repositories
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          while IFS=, read -r repo branch
          do
            # Extract repo name
            repo_name=$(basename $repo .git)
            
            # Set up the authenticated URL
            authenticated_repo_url=$(echo $repo | sed "s|https://|https://$GH_PAT:x-oauth-basic@|")
            
            # Clone the repository and checkout the specified branch
            git clone --branch $branch $authenticated_repo_url $repo_name

            # Zip the repository contents
            zip -r ${repo_name}.zip $repo_name

            # Upload to S3
            aws s3 cp ${repo_name}.zip s3://your-s3-bucket/${repo_name}.zip

            # Clean up
            rm -rf $repo_name
            rm ${repo_name}.zip
          done < .github/workflows/repositories.csv

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





- name: Verify CSV file exists
        run: |
          if [ ! -f .github/workflows/repositories.csv ]; then
            echo "Error: .github/workflows/repositories.csv not found!"
            exit 1
          else
            echo "CSV file found."
          fi




name: Process and Commit Changes

on:
  workflow_dispatch:

jobs:
  process_and_commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout this repository
      - name: Checkout this repository
        uses: actions/checkout@v2

      # Step 2: Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip jq awscli

      # Step 3: Configure AWS CLI
      - name: Configure AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1

      # Step 4: Extract repository name from zip file name and process it
      - name: Process Repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          zipfile=${{ github.event.inputs.zipfile }}
          
          # Extract repo name from the zip file name
          repo_name=$(basename "$zipfile" .zip)
          
          # Set up the repository URL
          repo="https://github.com/your-organization/$repo_name.git"
          authenticated_repo_url=$(echo $repo | sed "s|https://|https://$GH_PAT:x-oauth-basic@|")
          
          # Clone the repository and checkout the main branch
          git clone --branch main $authenticated_repo_url $repo_name
          
          # Download the processed zip file from S3
          aws s3 cp s3://your-s3-bucket/$zipfile $zipfile
          
          # Unzip the processed file into the repository directory
          unzip -o $zipfile -d $repo_name
          
          # Create a new branch for the processed data
          cd $repo_name
          new_branch="processed-branch"
          git checkout -b $new_branch
          
          # Add the unzipped files
          git add .
          
          # Commit the changes
          git commit -m "Add processed data from $zipfile"
          
          # Push the new branch to the remote repository
          git push $authenticated_repo_url $new_branch
          
          # Clean up
          cd ..
          rm -rf $repo_name
          rm $zipfile

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            
