Parameters:
  Environment:
    Type: String
    Description: Select Environment
    AllowedValues: [Frontend, Backend, SSS, Datalake, External]
    Default: Frontend

  VpcCidr:
    Type: String
    Default: 10.64.0.0/18

Mappings:
  NamePrefixMappings:
    Frontend:
      NamePrefix: 'FE'
    Backend:
      NamePrefix: 'BE'
    SSS:
      NamePrefix: 'SSS'
    Datalake:
      NamePrefix: 'DL'
    External:
      NamePrefix: 'EXT'

  TagsMappings:
    Frontend:
      Environment: 'Frontend'
      Department: 'IT'
    Backend:
      Environment: 'Backend'
      Department: 'Engineering'
    SSS:
      Environment: 'SSS'
      Department: 'Security'
    Datalake:
      Environment: 'Datalake'
      Department: 'Data'
    External:
      Environment: 'External'
      Department: 'External'

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: "Name"
          Value: 
            Fn::Sub:
              -  "${NamePrefix}-VPC"
              - NamePrefix: !FindInMap [NamePrefixMappings, !Ref Environment, NamePrefix]
        - Key: "Environment"
          Value: 
            !FindInMap [TagsMappings, !Ref Environment, Environment]
        - Key: "Department"
          Value: 
            !FindInMap [TagsMappings, !Ref Environment, Department]
